"""
models.py
Defines data models used across the Student Expense Tracker application.
"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class Expense:
    """
    Data model representing a single student expense record.
    
    Attributes:
        amount (float): The monetary value of the expense (must be positive).
        category (str): The category (e.g., Food, Travel, Education).
        expense_date (str): The date in YYYY-MM-DD format.
        description (str): Optional note or details about the expense.
        id (Optional[int]): Unique identifier generated by the database.
    """
    amount: float
    category: str
    expense_date: str
    description: str = ""
    id: Optional[int] = None

    def to_dict(self) -> dict:
        """Convert the Expense instance to a dictionary."""
        return {
            "id": self.id,
            "amount": self.amount,
            "category": self.category,
            "expense_date": self.expense_date,
            "description": self.description,
        }

    @classmethod
    def from_row(cls, row) -> "Expense":
        """Create an Expense instance from a SQLite row tuple (id, amount, category, date, desc)."""
        return cls(
            id=row[0],
            amount=float(row[1]),
            category=str(row[2]),
            expense_date=str(row[3]),
            description=str(row[4]) if row[4] is not None else "",
        )

